# Generated by Django 2.2 on 2020-11-22 05:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(default='Username', max_length=50)),
                ('email', models.EmailField(default='123@gmail.com', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('specialization', models.CharField(choices=[('select', 'Select'), ('aerospace_medicine', 'Aerospace Medicine'), ('allergies', 'Allergy and Immunology'), ('anaesthesia', 'Anaesthesia'), ('bariatric', 'Bariatric Surgery'), ('cardiologyInterventional', 'Cardiology - Interventional'), ('cardiologyNonInterventional', 'Cardiology - Non Interventional'), ('cardiologyVascular', 'Cardiothoracic And Vascular Surgery'), ('spinal', 'Centre For Spinal Diseases'), ('haematology&BMT', 'Clinical Haematology And BMT'), ('corneal', 'Corneal Transplant'), ('cmc', 'Critical Care Medicine'), ('dermatology', 'Dermatology And Cosmetology'), ('ent', 'Ear Nose Throat Head And Neck Surgery'), ('emergencyMedicine', 'Emergency Medicine'), ('endocrinology', 'Endocrinology'), ('generalSurgery', 'General Surgery'), ('infectius', 'Infectious Diseases'), ('internalMedicine', 'Internal Medicine'), ('ivf', 'In-Vitro Fertilisation (IVF)'), ('labMed', 'Laboratory Medicine'), ('liver', 'Liver Transplant & Hepatic Surgery'), ('maxillofacial', 'Maxillofacial Surgery'), ('medGas', 'Medical Gastroenterology'), ('medicalOncology', 'Medical Oncology'), ('minInvasiceGynecology', 'Minimally Invasive Gynecology'), ('neonatology', 'Neonatology'), ('nephrology', 'Nephrology'), ('neuroMod', 'Neuro Modulation'), ('diet', 'Nutrition & Dietetics'), ('neurology', 'Neurology'), ('neurosurgery', 'Neurosurgery'), ('obstetricsGynecology', 'Obstetrics And Gynecology'), ('ophthalmology', 'Ophthalmology'), ('orthpedics', 'Orthopedics & Joint Replacement'), ('painManage', 'Pain Management'), ('pediatric', 'Pediatric Surgery'), ('physio', 'Physiotherapy'), ('plastic', 'Plastic Surgery'), ('psych', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('renal', 'Renal Transplant'), ('reproductive&ivf', 'Reproductive Medicine & IVF'), ('rheumatology', 'Rheumatology'), ('robotic', 'Robotic Surgery'), ('skinCancer', 'Skin Cancer'), ('urology', 'Urology'), ('vascular', 'Vascular and endovascular surgery')], default='select', max_length=60)),
            ],
        ),
    ]
