# Generated by Django 2.2 on 2020-12-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
